### ISSUE TITLE
Environment setup

### ISSUE THREAD

**Issue by JohnApp-scRNA** [caleblareau/mgatk#24]
Hi there. I was excited to start using your tool but I'm having some issues with getting it going. I've installed mgatk, but when I get the following error

/home/anaconda3/envs/mgatk/lib/R/bin/exec/R: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory                             
ERROR: cannot find the following R package: {'Matrix', 'SummarizedExperiment', 'data.table', 'GenomicRanges'}                                                                                                      Install it in your R console and then try rerunning mgatk (but there may be other missing dependencies).     

I have these packages installed in my conda environment, and I still get this error. I'm used to performing analyses in python rather than R, so forgive me if this a stupid question, but any help in resolving it would be much appreciated.

Thanks,
John

**Comment by caleblareau** [comment]
So it looks like whatever R version is being sourced by your anaconda install is getting muddled. I don't think this is a stupid question at all and really isn't clear to me what you should do. 

If you want to run the tool and generate plain text files that I can help you post-process in R, try running the command with the `--skip-R` flag.

**Comment by caleblareau** [comment]
Closing the issue for now but @JohnApp-scRNA let me know if you couldn't figure this out

**Comment by JohnApp-scRNA** [comment]
Apologies for only just getting back to you. I was wondering if it would be possible for you to make a working conda environment available as a .yml file on your github, as I'm still having issues with R right now.

Thanks again,
John

**Comment by ncborcherding** [comment]
Just a follow up here - 

I was having the same issue as described above. After troubleshooting, I found that removing miniconda and ensuring my default python was set correctly. 

```
#Had 2 versions of miniconda for some reason
rm -rf ~/miniconda
rm -rf /Users/Nick/Library/r-miniconda

#Found and set my python version
ls -l /usr/local/bin/python*
ln -s -f /usr/local/bin/python3.9 /usr/local/bin/python
```

Now mgatk works like a charm. 

Nick
