### ISSUE TITLE
mgatk does not generate .rds output files

### ISSUE THREAD

**Issue by mjprzybilla** [caleblareau/mgatk#32]
Hi Caleb, 

amazing work, providing this tool for looking into MtDNA variants! 

Ive been running mgatk on samples profiled by 10X scATAC-seq, but have encountered some issues when looking at the output files. In some cases, although all previous files have been successfully generated and the workflow has been executed correctly ( to the snakemake log files), the `.rds` objects are missing. 

```
Tue Mar 23 16:45:56 CET 2021: Starting analysis with mgatk
Tue Mar 23 16:45:56 CET 2021: Processing samples with 12 threads
Tue Mar 23 17:59:54 CET 2021: mgatk successfully processed the supplied .bam files
Tue Mar 23 18:04:05 CET 2021: Successfully created final output files
Tue Mar 23 18:04:08 CET 2021: Intermediate files successfully removed.
Tue Mar 23 20:11:49 CET 2021: Starting analysis with mgatk
Tue Mar 23 20:11:49 CET 2021: Processing samples with 12 threads
Tue Mar 23 21:25:31 CET 2021: mgatk successfully processed the supplied .bam files
Tue Mar 23 21:25:40 CET 2021: Successfully created final output files
Tue Mar 23 21:25:42 CET 2021: Intermediate files successfully removed.
```

I am not sure what's wrong, as apart from the missing files, everything seems to be executed correctly. Any assistance or thoughts would be welcome! :) 

Thanks so much in advance, 
Moritz

**Comment by caleblareau** [comment]
Hmm I'm sufficiently flummoxed... did you cat the log files from snakemake? Can you show me what ls -lRth is of the output directory?

**Comment by mjprzybilla** [comment]
Nevermind! Seems like the problem was resulting from the fact, that I was writing the output files from two samples from the same patient in a patient, rather than sample-specific output folder. In the shared folder, only one `.rds` object was created - however, creating a sample-specific folder worked perfectly fine! Many thanks though!
