### ISSUE TITLE
Clarification on marking duplicates

### ISSUE THREAD

**Issue by cnk113** [caleblareau/mgatk#34]
Hello,

I was wondering if the duplicate marking picard was at cell resolution? I didn't realize until yesterday with the release of cellranger-atac 2.0 that CR duplicate marking was at bulk resolution. I'm assuming mgatk it is at cell resolution?

Thanks,
Chang

**Comment by caleblareau** [comment]
Hi Chang,

Yes we are operating at the cell resolution— I didn’t agree with how CR was previously operating, and I’m glad that the new version addresses this.

Caleb


On May 5, 2021, at 4:04 PM, Chang Kim ***@***.******@***.***>> wrote:



Hello,

I was wondering if the duplicate marking picard was at cell resolution? I didn't realize until yesterday with the release of cellranger-atac 2.0 that CR duplicate marking was at bulk resolution. I'm assuming mgatk it is at cell resolution?

Thanks,
Chang

**Comment by cnk113** [comment]
Ah that's great, I didn't want to rerun it. I guess in the future you might not need to run mark duplicates within mgatk or maybe add a parameter to use the existing marked duplicates?

**Comment by caleblareau** [comment]
Well, the CellRanger v2 update only applies to how they process/produce the fragments file but the bam is the same

On May 5, 2021, at 4:30 PM, Chang Kim ***@***.******@***.***>> wrote:



Ah that's great, I didn't want to rerun it. I guess in the future you might not need to run mark duplicates within mgatk or maybe add a parameter to use the existing marked duplicates?

**Comment by cnk113** [comment]
Hmm, the 10X bioinformatician was saying the read pairs are marked duplicates. I'll follow up with them for further clarification, thanks!

**Comment by caleblareau** [comment]
Ah, well, mgatk ignore thes the mark duplicate tags in the bam existing and computes it de novo.

On May 5, 2021, at 5:30 PM, Chang Kim ***@***.******@***.***>> wrote:



Hmm, the 10X bioinformatician was saying the read pairs are marked duplicates. I'll follow up with them for further clarification, thanks!

**Comment by cnk113** [comment]
One more thing, I have a custom library that has overlapping reads with the same UMI, would UMI deduplication setting work here? Ideally the overlapping regions would be picked for the highest quality.

**Comment by caleblareau** [comment]
When you specify a UMI tag in mgatk, the software deduplicates reads using PIcard Tools MarkDuplicates, which retains the read with the highest mean base quality.
