### ISSUE TITLE
Missing input files for rule call_variants

### ISSUE THREAD

**Issue by FloWuenne** [caleblareau/mgatk#35]
Hi @caleblareau ,

thanks for developing this great package!

I wanted to try and run a test of using mgatk on 10x mouse scRNA-seq data.

I used the .bam file from the following public dataset:
https://www.10xgenomics.com/resources/datasets/1-k-heart-cells-from-an-e-18-mouse-v-3-chemistry-3.0.0

I installed mgatk using venv and tried to run the following:

```
ref_dir="/test_data"
mgatk tenx --mito-genome GRCm38 \
        -i ${ref_dir}/heart_1k_v3_possorted_genome_bam.bam \
        -n tenx_heart_test -o tenx_heart_test_mgatk \
        -c 1 \
        -ub UB \
        -bt CB \
        -b ${ref_dir}/filtered_feature_bc_matrix/barcodes.tsv \
        --snake-stdout \
        --keep-temp-files
```

I got the following error and don't know how to address this. 

Thanks for your help! 

```
Wed May 12 14:57:09 EDT 2021: mgatk v0.6.1
Wed May 12 14:57:09 EDT 2021: Found bam file: /test_data/heart_1k_v3_possorted_genome_bam.bam for genotyping.
Wed May 12 14:57:09 EDT 2021: Found file of barcodes to be parsed: /test_data/filtered_feature_bc_matrix/barcodes.tsv
[W::hts_idx_load3] The index file is older than the data file: /test_data/heart_1k_v3_possorted_genome_bam.bam.bai
Wed May 12 14:57:10 EDT 2021: User specified mitochondrial genome matches .bam file
[W::hts_idx_load3] The index file is older than the data file: /test_data/heart_1k_v3_possorted_genome_bam.bam.bai
Wed May 12 15:00:04 EDT 2021: Finished determining/splitting barcodes for genotyping.
Wed May 12 15:00:04 EDT 2021: Genotyping samples with 1 threads
Building DAG of jobs...
MissingInputException in line 160 of /mgatk_venv/lib/python3.8/site-packages/mgatk/bin/snake/Snakefile.tenx:
Missing input files for rule call_variants:
tenx_heart_test_mgatk/final/chrM_refAllele.txt
Error in checkGrep(grep(".A.txt", files)) : 
  Improper folder specification; file missing / extra file present. See documentation
Calls: importMito -> checkGrep
Execution halted
```

**Comment by caleblareau** [comment]
Thanks! Could you send `ls -lR` of the output so I can potentially see where things failed?

On May 12, 2021, at 12:19 PM, Florian Wuennemann ***@***.******@***.***>> wrote:



Hi @caleblareau<https://github.com/caleblareau> ,

thanks for developing this great package!

I wanted to try and run a test of using mgatk on 10x mouse scRNA-seq data.

I used the .bam file from the following public dataset:
https://www.10xgenomics.com/resources/datasets/1-k-heart-cells-from-an-e-18-mouse-v-3-chemistry-3.0.0

I installed mgatk using venv and tried to run the following:

ref_dir="/test_data"
mgatk tenx --mito-genome GRCm38 \
        -i ${ref_dir}/heart_1k_v3_possorted_genome_bam.bam \
        -n tenx_heart_test -o tenx_heart_test_mgatk \
        -c 1 \
        -ub UB \
        -bt CB \
        -b ${ref_dir}/filtered_feature_bc_matrix/barcodes.tsv \
        --snake-stdout \
        --keep-temp-files


I got the following error and don't know how to address this.

Thanks for your help!

Wed May 12 14:57:09 EDT 2021: mgatk v0.6.1
Wed May 12 14:57:09 EDT 2021: Found bam file: /test_data/heart_1k_v3_possorted_genome_bam.bam for genotyping.
Wed May 12 14:57:09 EDT 2021: Found file of barcodes to be parsed: /test_data/filtered_feature_bc_matrix/barcodes.tsv
[W::hts_idx_load3] The index file is older than the data file: /test_data/heart_1k_v3_possorted_genome_bam.bam.bai
Wed May 12 14:57:10 EDT 2021: User specified mitochondrial genome matches .bam file
[W::hts_idx_load3] The index file is older than the data file: /test_data/heart_1k_v3_possorted_genome_bam.bam.bai
Wed May 12 15:00:04 EDT 2021: Finished determining/splitting barcodes for genotyping.
Wed May 12 15:00:04 EDT 2021: Genotyping samples with 1 threads
Building DAG of jobs...
MissingInputException in line 160 of /mgatk_venv/lib/python3.8/site-packages/mgatk/bin/snake/Snakefile.tenx:
Missing input files for rule call_variants:
tenx_heart_test_mgatk/final/chrM_refAllele.txt
Error in checkGrep(grep(".A.txt", files)) :
  Improper folder specification; file missing / extra file present. See documentation
Calls: importMito -> checkGrep
Execution halted

**Comment by FloWuenne** [comment]
Thanks for the quick reply! 

I assume  you mean to run `ls -lR` in the output folder?

This is the output of that command: 

```
total 20
drwxrwxr-x 2 florian florian 4096 May 12 14:57 fasta
drwxrwxr-x 2 florian florian 4096 May 12 13:04 final
drwxrwxr-x 4 florian florian 4096 May 12 13:07 logs
drwxrwxr-x 4 florian florian 4096 May 12 13:07 qc
drwxrwxr-x 8 florian florian 4096 May 12 15:00 temp

./fasta:
total 24
-rw-rw-r-- 1 florian florian 16575 May 12 14:57 MT.fasta
-rw-rw-r-- 1 florian florian    17 May 12 14:57 MT.fasta.fai

./final:
total 120
-rw-rw-r-- 1 florian florian 119286 May 12 14:57 MT_refAllele.txt

./logs:
total 16
-rw-rw-r-- 1 florian florian 1067 May 12 15:00 base.mgatk.log
drwxrwxr-x 2 florian florian 4096 May 12 13:07 filterlogs
drwxrwxr-x 2 florian florian 4096 May 12 13:07 rmdupslogs
-rw-rw-r-- 1 florian florian  610 May 12 15:00 tenx_heart_test.parameters.txt
-rw-rw-r-- 1 florian florian    0 May 12 13:07 tenx_heart_test.snakemake_tenx.log

./logs/filterlogs:
total 0

./logs/rmdupslogs:
total 0

./qc:
total 8
drwxrwxr-x 2 florian florian 4096 May 12 13:07 depth
drwxrwxr-x 2 florian florian 4096 May 12 13:07 quality

./qc/depth:
total 0

./qc/quality:
total 0

./temp:
total 24
drwxrwxr-x 2 florian florian 4096 May 12 15:00 barcoded_bams
drwxrwxr-x 2 florian florian 4096 May 12 14:57 barcode_files
drwxrwxr-x 2 florian florian 4096 May 12 15:00 quality
drwxrwxr-x 2 florian florian 4096 May 12 15:00 ready_bam
drwxrwxr-x 2 florian florian 4096 May 12 15:00 sparse_matrices
drwxrwxr-x 2 florian florian 4096 May 12 15:00 temp_bam

./temp/barcoded_bams:
total 213532
-rw-rw-r-- 1 florian florian 218644830 May 12 15:00 barcodes.1.bam
-rw-rw-r-- 1 florian florian       616 May 12 15:00 barcodes.1.bam.bai

./temp/barcode_files:
total 20
-rw-rw-r-- 1 florian florian 19209 May 12 14:57 barcodes.1.txt

./temp/quality:
total 0

./temp/ready_bam:
total 0

./temp/sparse_matrices:
total 0

./temp/temp_bam:
total 0

```

**Comment by caleblareau** [comment]
hmmm hard to say what's failing right now; is java installed on your machine and configured? Could you all potentially try the `bcall` option with say maybe 10 barcodes to make things faster?

**Comment by FloWuenne** [comment]
Java is installed on my machine:

```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

Running the same data using the bcall option with 10 barcodes does work without problems:

```
mgatk bcall --mito-genome GRCm38 \
        -i ${ref_dir}/heart_1k_v3_possorted_genome_bam.bam \
        -n tenx_heart_test -o tenx_heart_test_mgatk \
        -c 1 \
        -ub UB \
        -bt CB \
        -b ${ref_dir}/filtered_feature_bc_matrix/subset_barcodes.tsv \
        --snake-stdout \
        --keep-temp-files
```

Let me know if you want me to run any more tests to figure out what's going on with the tenx command! 

Thanks for the help!

**Comment by caleblareau** [comment]
Does `tenx` with 10 barcodes or so work?

**Comment by FloWuenne** [comment]
No, unfortunately not. I just tried to run tenx with the same subset of barcodes as bcall and it failed with the same error as the full barcode list...

```
Building DAG of jobs...
MissingInputException in line 160 of /home/florian/Postdoc/testing_tools/mgatk/mgatk_venv/lib/python3.8/site-packages/mgatk/bin/snake/Snakefile.tenx:
Missing input files for rule call_variants:
tenx_heart_test_mgatk/final/chrM_refAllele.txt
Error in checkGrep(grep(".A.txt", files)) : 
  Improper folder specification; file missing / extra file present. See documentation
Calls: importMito -> checkGrep
Execution halted
```

**Comment by caleblareau** [comment]
sorry for the delayed response-- as I understand where this is now, `bcall` works but not `tenx` mode; would that be the case for the full dataset? Since there isn't as much data for scRNA, that may be the best solution. I'm not seeing what could be obviously wrong otherwise at the moment...

**Comment by Jincheng2009** [comment]
Hi, I am getting the same error using mgatk tool, and this is tenx mode as well.

**Comment by Jincheng2009** [comment]
I just troubleshoot the code and here might be the cause of the error:
I am using GRCh38 as the reference genome, and after the reference allele generation, the file has a name "MT_refAllele.txt",
However, in the call_variant script, the reference file is hard-coded as chrM_refAllele.txt.

# call potential variantsvariants = gather_possible_variants(base_coverage_dict, MGATK_OUT_DIR + 'chrM_refAllele.txt')

**Comment by caleblareau** [comment]
@Jincheng2009 @FloWuenne I made a couple of edits in v0.6.3 (will be on PyPi shortly) that should solve this. Please comment back on this thread if not.
