### ISSUE TITLE
can be used for snATAC?

### ISSUE THREAD

**Issue by AnjaliC4** [caleblareau/mgatk#41]
Hi, thanks for the tool! Have you guys tried using mgatk for single-nucleus ATAC-seq? How do you think this would perform for snATAC? I guess assumption would be that mtDNA in snATAC come from mitochondria of the same cell?!

Thanks

**Comment by caleblareau** [comment]
Hi Anjali,

We’ve tried but never had a successful application unfortunately. By definition, the snATAC strips out the mitochondrial so a) there is very little captured; b) there is non-specific signal as you suggested. 

The code will run but I can’t recommend spending very much, if any, time on interpreting the analysis as it is unlikely to be fruitful!
