### ISSUE TITLE
Integrating multiple data

### ISSUE THREAD

**Issue by dawe** [caleblareau/mgatk#47]
Hello, I am applying `mgatk` on several datasets and at a certain point I will need to integrate them. Given that the same cell barcode can be in different experiments, I was thinking I could concatenate the `rds` objects so that every cell gets a unique name across multiple datasets. Is this legit for downstream analysis? I thought I could then perform a single run of variant calling on the merged dataset.
I admit I'm not proficient with R, so any hint on how to merge multiple `SummarizedExperiment` objects is much appreciated :-)
Another question that comes after integration is how to evaluate the similarities among cells. Once variants have been identified (and filtered), would it be appropriate to calculate distances on the `allele_frequency` values in the `data` slot?

**Comment by caleblareau** [comment]
Sorry for the delay! 

`SummarizedExperiments` are pretty great; what I typically do is something like this..

```
SE1 <- readRDS("mgatk_SE1.rds")
SE2 <- readRDS("mgatk_SE2.rds")
colnames(SE2) <- gsub("-1", "-2", colname(SE2)
SE <- cbind(SE1, SE2)
```

So in short, you can `cbind` objects and it will automatically combine all of the nested matrices as well as rename the cells via changing the `colnames` of the SE object. Some people use more sophisticated conventions when reannotating cells, such as `paste`-ing a descriptor associated with the library. This isn't unlike what one would have to do in Seurat if you had multiple libraries that you were trying to analyze concurrently!

**Comment by dawe** [comment]
Thanks, I have solved with `cbind()` and changing `colnames` so that they match names in `AnnData` I am using.
