### ISSUE TITLE
Using Mgatk for non mitochondrial sequences

### ISSUE THREAD

**Issue by suneetz** [caleblareau/mgatk#51]
Hi,

I tried to run Mgatk on my data (10x scRNA seq) and I believe since the cells aren't very enriched for mtDNA i wasn't able to find distinct variants to identify subclones. Do you know if I can use the Mgatk program for non mitochondrial sequences?

Thank you,

Sunita

**Comment by caleblareau** [comment]
Hi Sunita,

No, mgatk is specialized for mitochondrial genomes and does not apply to other genomes. Other tools such as Vartrix, freebayes, Souporcell, Vireo, etc. have been established and designed for nuclear variant analysis.
