### ISSUE TITLE
Error run mgatk

### ISSUE THREAD

**Issue by tianchen2019** [caleblareau/mgatk#56]
i am sorry to bother you.
My code is as follows 
```
source ~/app/anaconda3/envs/mgatk/bin/activate
mgatk tenx -i /Sshare/tianchen/AML/3_sample_buce_merge/ZLH_10x_2/outs/possorted_bam.bam \
  -n ZLH -o ZLH_mgatk_50bp -c 8 \
  -bt CB -b /Sshare/tianchen/AML/3_sample_buce_merge/ZLH_10x_2/outs/filtered_peak_bc_matrix/barcodes.tsv
```
the error is as follows. 
```
Fri Feb 11 16:21:19 CST 2022: mgatk v0.6.2
Fri Feb 11 16:21:20 CST 2022: Found bam file: /Sshare/tianchen/AML/3_sample_buce_merge/ZLH_10x_2/outs/possorted_bam.bam for genotyping.
Fri Feb 11 16:21:20 CST 2022: Found file of barcodes to be parsed: /Sshare/tianchen/AML/3_sample_buce_merge/ZLH_10x_2/outs/filtered_peak_bc_matrix/barcodes.tsv
Fri Feb 11 16:21:20 CST 2022: User specified mitochondrial genome matches .bam file
Fri Feb 11 19:25:14 CST 2022: Finished determining/splitting barcodes for genotyping.
Fri Feb 11 19:25:14 CST 2022: Genotyping samples with 8 threads
Error in checkGrep(grep(".A.txt", files)) :
  Improper folder specification; file missing / extra file present. See documentation
Calls: importMito -> checkGrep
```
the snakemake_tenx.log is as follows.
```
Building DAG of jobs...
Error: Directory cannot be locked. Please make sure that no other Snakemake process is trying to create the same files in the following directory:
/fshare2/tianchen/AML/mt_coverage/3_sample_mgatk
If you are sure that no other instances of snakemake are running on this directory, the remaining lock was likely caused by a kill signal or a power loss. It can be removed with the --unlock argument.
```

**Comment by caleblareau** [comment]
Can you send an `ls -lRth` of the output folder?

**Comment by tianchen2019** [comment]
> Can you send an `ls -lRth` of the output folder?

I have solved this problem. But a new phenomenon emerged. I have a sample that finds many G>C mutations using mgatk's method. 
![image](https://user-images.githubusercontent.com/46451175/154438120-a36893fd-8930-4612-ac21-2753e783e97f.png)
However, other samples did not show this phenomenon. 
![image](https://user-images.githubusercontent.com/46451175/154440570-87975747-5b9f-465b-80ef-ab61319db3c5.png)

**Comment by tianchen2019** [comment]
> 

My sample is from the bone marrow of leukemia patients.  And the sequencing method is mtscATAC-seq. The sequencing is PE50.
mtscATAC-seq was performed according to the method of this article. 
https://www.nature.com/articles/s41587-020-0645-6
Massively parallel single-cell mitochondrial DNA genotyping and chromatin profiling

**Comment by caleblareau** [comment]
Wild-- I've never seen anything like this. I'm not sure what even to suggest how to help-- this is very unusual.

**Comment by caleblareau** [comment]
I'm closing this issue now as I really don't have a comment but @tianchen2019 if you have anything else that you can uncover about this sample, do let me know
