### ISSUE TITLE
mgatk-del-find won't run

### ISSUE THREAD

**Issue by mrland99** [caleblareau/mgatk#64]
**Describe the bug**
Trying to run `mgatk-del-find` but running into import problem for example:
```
mgatk-del-find --help
  File "/home/landm/anaconda3/envs/scri/bin/mgatk-del-find", line 5
    from mgatk.del.clifind import main
```
or
```
mgatk-del-find -i /data/peer/sohailn/collaborators/sfeira/RC-1652_T4i5_D6_multiome/cr-arc-results-with-atac-mito/atac_possorted_bam.bam 
  File "/home/landm/anaconda3/envs/scri/bin/mgatk-del-find", line 5
    from mgatk.del.clifind import main
```

Seems like Python version `3.9.12` is very unhappy with using `del` as a folder name.  I noticed when I manually change the folder name after cloning the repo and reinstalling the import works (e.g. `from mgatk.newname.clifind import main`). Not sure why it is, kind of weird. I will say this one fix still causes other downstream errors since it is looking for the `mgatk.del` module so would need to propgate changes everywhere.

**To Reproduce**
pip installed mgatk on conda environment using Python version `3.9.12`

**Comment by caleblareau** [comment]
I guess `del` has a special meaning in python...

https://www.toppr.com/guides/python-guide/questions/what-is-del-in-python/#:~:text=What%20is%20del%20in%20Python,the%20item%20have%20been%20destroyed. 

okay it seems like an easy fix as you suggested to update the folder name and then the code that imports various functions; I should be able to do that in the next few days and then put a new version on `pip`. Thanks for the note

**Comment by caleblareau** [comment]
I bumped the pypi version (`0.6.7`) that hopefully fixes this. @mrland99 can you confirm?

**Comment by mrland99** [comment]
Looks like this fixed the bug. Ran without problems. Thanks for the quick fix Caleb!
