### ISSUE TITLE
missing output files 

### ISSUE THREAD

**Issue by gddhouse** [caleblareau/mgatk#67]
**Describe the bug**

the "out/final" path didn't have "*.variant_stats.tsv.gz", "*.cell_heteroplasmic_df.tsv.gz", "*.vmr_strand_plot.png" these three files.

**the command code i  used is as following**

mgatk bcall -i ${bam_data} -n $5 -o ${out} -c 10 -bt DB -b ${barcode_uniq}  -z -g ${g}

**log file**

Mon Apr 03 15:36:23 CST 2023: mgatk v0.6.6
Mon Apr 03 15:36:25 CST 2023: Found bam file: /hwfssz1/ST_SUPERCELLS/P22Z10200N0664/xieyue/04.MM/03fist_batch/01data/ALL-130-P-230301-ATAC-1.bam for genotyping.
Mon Apr 03 15:36:25 CST 2023: Found file of barcodes to be parsed: /hwfssz1/ST_SUPERCELLS/P22Z10200N0664/xieyue/04.MM/03fist_batch/01data/ALL-130-P-230301-ATAC-1.fragments_uniq.tsv
Mon Apr 03 15:36:26 CST 2023: User specified mitochondrial genome matches .bam file
Mon Apr 03 17:55:39 CST 2023: Finished determining/splitting barcodes for genotyping.
Mon Apr 03 18:00:12 CST 2023: Genotyping samples with 10 threads

**Comment by caleblareau** [comment]
This is the intended behavior-- only in `tenx` mode are these additional files produced

**Comment by gddhouse** [comment]
> This is the intended behavior-- only in `tenx` mode are these additional files produced

will u add this function in bcall?
