### ISSUE TITLE
test_cli.py uses removed `md5` module

### ISSUE THREAD

**Issue by rekado** [caleblareau/mgatk#68]
**Describe the bug**

The file test_cli.py uses the module `md5`, which has been removed from Python 3.

**To Reproduce**
Run the test suite with `pytest`.

**Expected behavior**
Tests pass.

**Additional context**

The fix is simple:

- replace `import md5` with `from hashlib import md5`
- replace `md5.new` with `md5`
- replace `digest` with `hexdigest`

**Comment by caleblareau** [comment]
Thanks-- fortunately only in the test code rather than the main package. I've updated this script in the latest commit.
