### ISSUE TITLE
input cell number does not equal to output cell number

### ISSUE THREAD

**Issue by TuoCai2000** [caleblareau/mgatk#69]
Hi,thank you for developing mgatk.
I have 183 bamfiles from smart-seq2, and I run the code：mgatk call -i ./bamfiles/ -g hg38 -q 30 ;
which does not produce any error and the output files looks good!
However,when I checked the depth file and the .rds files, I only found 11 cells.
Can you tell me why and how to solve it ? Thank you so much !!

**Comment by caleblareau** [comment]
there is an internal filter to remove cells with 0 mitochondrial reads (perhaps either some cells had an alternate chrM/MT chromosome or had very few mitochondrial reads after the q 30 filter). For a cell that isn't on there, can you verify the mitochondrial chromosome name and tha there are lots of reads there?

**Comment by TuoCai2000** [comment]
Thank you! 
I verified the cells that are not on there, they all seems to have a good coverage of mitochondrial chromosome reads. I also remove the parameter:q30 , but got the same result. Now I have no idea how to solve this problem.
Thank you so much!

**Comment by caleblareau** [comment]
Can you upload a minimal set of say 2-3 cells, some that do and some that don't get genotyped? I'll have to look into it more directly

**Comment by TuoCai2000** [comment]
Oh sorry，I just tried to upload 2 bamfiles but failed.
So I just used 2 cells that don't get genotyped to get another run and I get the result .
I wonder if I can separate the 183 cells and even run it per cell (a cell per run / 183 runs) and merge the result? I do not know if it works for me.
Thank you so much!

**Comment by caleblareau** [comment]
how are the bams formatted? its 1 file per cell right?

**Comment by caleblareau** [comment]
could you maybe share the logs and `ls -lRt` of the output folder when you tried the full genotyping?

**Comment by TuoCai2000** [comment]
yes，they are the output of smart-seq2.
<img width="552" alt="image" src="https://github.com/caleblareau/mgatk/assets/94456986/b0b68bd8-33ae-4bdc-90d7-138c8c4b199e">
<img width="1136" alt="image" src="https://github.com/caleblareau/mgatk/assets/94456986/bcefe93b-c92c-47f6-b91f-d6c5d57fd1c7">

**Comment by TuoCai2000** [comment]
Thank you so much!I have solved this problem!It seems like I do not have much space on the node
