### ISSUE TITLE
What is per-position coverage?

### ISSUE THREAD

**Issue by FionaMoon** [caleblareau/mgatk#79]
Hi All,
I'm new to mgatk and I'm quite confused about "per-position coverage".
After running `variant_calling.R` following https://caleblareau.github.io/bits/ATAC/CRC-tumor.html, I got the result(SummarizedExperiment object) which contains the row "mean_coverage".
The "mean_coverage" ranges from 0.149243 to 400+.
I don't know how to understand coverage in one position. Maybe it's depth but not coverage? 

Thank you in advance!

**Comment by caleblareau** [comment]
the value is per cell right? its the mean coverage per position for that cell. So a value of 10 means "average of 10 reads per position for this cell". (I'm not entirely sure that I've used the terms depth and coverage fully consistently so depth may be the best interpretation)

**Comment by caleblareau** [comment]
The per-position coverage should come from the assays()[["coverage"]] matrix and it should be an integer value.

**Comment by FionaMoon** [comment]
Thank you!
I can understand it now.
