### ISSUE TITLE
process mtDNA genotyping using scATAC-seq data from 10x multiome 

### ISSUE THREAD

**Issue by pxh251** [caleblareau/mgatk#91]
I am following the Wiki to run: (see the screenshot attached)
<img width="1125" alt="Screenshot 2024-03-22 at 12 32 14 PM" src="https://github.com/caleblareau/mgatk/assets/93609961/fac4427f-86f7-4b16-bd86-058f4236134d">

All my bam and tsv files are generated correctly but when I am trying run the .sh file attached, I encountered a .slurm file and it has been just stuck here forever.
<img width="1531" alt="Screenshot 2024-03-22 at 12 34 25 PM" src="https://github.com/caleblareau/mgatk/assets/93609961/abab3b5c-c267-4993-a5af-8e7edf2bc530">

Note: Since my scATAC-seq data is from the 10x multiome, is there a difference when processing scATAC from 10x multiome vs. only scATAC alone? 

I really appreciate your help!

**Comment by caleblareau** [comment]
you want to specify the mitochondrial fasta is all. If you are using standard GRCh38, its actually built in (`-g hg38`). It's stalling out b/c you gave it the full genome as a reference instead of just mito

**Comment by pxh251** [comment]
Thank you very much for your response! I replace my fasta with -g hg38. However, it got stuck on the following step without any error reported: 
<img width="1528" alt="Screenshot 2024-03-22 at 4 57 54 PM" src="https://github.com/caleblareau/mgatk/assets/93609961/267e4300-2c62-4204-ad6a-b13b94aa594a">
May I ask about what's your thought on this? Thanks!

**Comment by pxh251** [comment]
> Thank you very much for your response! I replace my fasta with -g hg38. However, it got stuck on the following step without any error reported: <img alt="Screenshot 2024-03-22 at 4 57 54 PM" width="1528" src="https://private-user-images.githubusercontent.com/93609961/316166689-267e4300-2c62-4204-ad6a-b13b94aa594a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NzM0MTcsIm5iZiI6MTcxMTQ3MzExNywicGF0aCI6Ii85MzYwOTk2MS8zMTYxNjY2ODktMjY3ZTQzMDAtMmM2Mi00MjA0LWFkNmEtYjEzYjk0YWE1OTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE3MTE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NDc4MzZjNTM2NDYxM2I5MjQ0OTJlNDRmYTFhNjQ2N2FiZjdjOGIwY2QyNWM1YTBjMTg4MTkwOWM1MTY2MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xySDpFZsp2i97-k70R_681U5ELVgqk_yucx2O6pyECU"> May I ask about what's your thought on this? Thanks!

Can I quickly follow up on this please? Thank you so much!

**Comment by caleblareau** [comment]
Hey sorry it’s not clear what you mean getting stuck here. It looks like it’s working as planned… is there output in the snakemake log?

On Mar 26, 2024, at 1:12 PM, pxh251 ***@***.***> wrote:

﻿

Thank you very much for your response! I replace my fasta with -g hg38. However, it got stuck on the following step without any error reported: [Screenshot 2024-03-22 at 4 57 54 PM] <https://private-user-images.githubusercontent.com/93609961/316166689-267e4300-2c62-4204-ad6a-b13b94aa594a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NzM0MTcsIm5iZiI6MTcxMTQ3MzExNywicGF0aCI6Ii85MzYwOTk2MS8zMTYxNjY2ODktMjY3ZTQzMDAtMmM2Mi00MjA0LWFkNmEtYjEzYjk0YWE1OTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE3MTE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM5NDc4MzZjNTM2NDYxM2I5MjQ0OTJlNDRmYTFhNjQ2N2FiZjdjOGIwY2QyNWM1YTBjMTg4MTkwOWM1MTY2MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xySDpFZsp2i97-k70R_681U5ELVgqk_yucx2O6pyECU>  May I ask about what's your thought on this? Thanks!

Can I quickly follow up on this please? Thank you so much!

**Comment by pxh251** [comment]
there's no output at all (no files generated, including any log files). The job just stopped by itself after 10min.

**Comment by caleblareau** [comment]
Probably rm -rf the .snakemake folder and retry then?

Caleb

On Mar 26, 2024, at 1:32 PM, pxh251 ***@***.***> wrote:



there's no output at all (no files generated, including any log files). The job just stopped by itself after 10min.
