### ISSUE TITLE
mgatk did not detect homoplasmic mutations

### ISSUE THREAD

**Issue by chaiepi** [caleblareau/mgatk#97]
Using mgatk to detect mitochondrial mutation sites in the mtscATAC-seq data (30x mean coverage of mtDNA) of mouse kidney tissue, I obtained low-quality mutations and genuine mutation sites, but did not observe homoplasmic mutations. Is this result credible?
![mut80 vmr_strand_plot](https://github.com/user-attachments/assets/9e8c5f0e-2fa2-43a7-9bee-84aa062fa7e0)

**Comment by caleblareau** [comment]
This has been consistent with my other experiences looking at mouse data that there are often no homoplasmic variants. You could double check by importing the variants.stats file and then sorting by descending mean to see if anything is higher than say 0.8, which could be a homoplasmic variant. But off hand, I don't see any reason for concern

**Comment by chaiepi** [comment]
Thank you for your reply. By examining the variant_stats file, I did not observe any sites with means greater than or close to 0.8. The target site had a mean of 0.54 (this site was edited), and the means of the other sites were all below 0.1. This may suggest that mgatk did not detect homoplasmic variants in the mouse kidney.

**Comment by caleblareau** [comment]
Ok then I’m inclined to say there aren’t homoplasmic variants then in your genomes. 

If you want to double check this, you could either modify the reference that is supplied to mgatk (supply a custom fasta) and/or run a bulk variant caller like FreeBayes and see what they return. I’ve never had an issue with missing homoplasmic variants in the past!
